package com.leo.demo.test1;

public interface SysContants {

	String ALL_TRACKS = "ALL_TRACKS";
	String ALL_TRACKS_PARQUET = "ALL_TRACKS_PARQUET";
	String CERTIFICATION_TRACK_PARQUET = "CERTIFICATION_TRACK_PARQUET";
	String CAP_MAC_TRACK_ORIGINAL = "CAP_MAC_TRACK_ORIGINAL";
	String CAP_MAC_TRACK = "CAP_MAC_TRACK";
	String ZM_TRACK = "ZM_TRACK";// zm_track
	String AUTH_TRACK = "AUTH_TRACK";
	String FRIEND_RELATION = "FRIEND_RELATION";
	String RELATION = "RELATION";
	String RELATION_PARQUET = "RELATION_PARQUET";
	String ON_OFF_LINE = "ON_OFF_LINE";
	String NET_ACT_LOG = "NET_ACT_LOG";
	String NET_ACTIVITY_TRACK = "NET_ACTIVITY_TRACK";
	String IM_CHAT_CONTENT = "IM_CHAT_CONTENT";
	String CERTIFICATION = "CERTIFICATION";
	String COMMON_CONTENT = "COMMON_CONTENT";
	
}