/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.leolian.thrift.demo;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused", "restriction"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-02-15")
public class ThriftRequest implements org.apache.thrift.TBase<ThriftRequest, ThriftRequest._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftRequest");

  private static final org.apache.thrift.protocol.TField COMMOND_FIELD_DESC = new org.apache.thrift.protocol.TField("commond", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField REQUEST_PARAM_FIELD_DESC = new org.apache.thrift.protocol.TField("requestParam", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftRequestTupleSchemeFactory();

  public java.lang.String commond; // required
  public java.nio.ByteBuffer requestParam; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMMOND((short)1, "commond"),
    REQUEST_PARAM((short)2, "requestParam");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COMMOND
          return COMMOND;
        case 2: // REQUEST_PARAM
          return REQUEST_PARAM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.REQUEST_PARAM};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMMOND, new org.apache.thrift.meta_data.FieldMetaData("commond", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REQUEST_PARAM, new org.apache.thrift.meta_data.FieldMetaData("requestParam", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftRequest.class, metaDataMap);
  }

  public ThriftRequest() {
  }

  public ThriftRequest(
    java.lang.String commond)
  {
    this();
    this.commond = commond;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftRequest(ThriftRequest other) {
    if (other.isSetCommond()) {
      this.commond = other.commond;
    }
    if (other.isSetRequestParam()) {
      this.requestParam = org.apache.thrift.TBaseHelper.copyBinary(other.requestParam);
    }
  }

  public ThriftRequest deepCopy() {
    return new ThriftRequest(this);
  }

  public void clear() {
    this.commond = null;
    this.requestParam = null;
  }

  public java.lang.String getCommond() {
    return this.commond;
  }

  public ThriftRequest setCommond(java.lang.String commond) {
    this.commond = commond;
    return this;
  }

  public void unsetCommond() {
    this.commond = null;
  }

  /** Returns true if field commond is set (has been assigned a value) and false otherwise */
  public boolean isSetCommond() {
    return this.commond != null;
  }

  public void setCommondIsSet(boolean value) {
    if (!value) {
      this.commond = null;
    }
  }

  public byte[] getRequestParam() {
    setRequestParam(org.apache.thrift.TBaseHelper.rightSize(requestParam));
    return requestParam == null ? null : requestParam.array();
  }

  public java.nio.ByteBuffer bufferForRequestParam() {
    return org.apache.thrift.TBaseHelper.copyBinary(requestParam);
  }

  public ThriftRequest setRequestParam(byte[] requestParam) {
    this.requestParam = requestParam == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(requestParam.clone());
    return this;
  }

  public ThriftRequest setRequestParam(java.nio.ByteBuffer requestParam) {
    this.requestParam = org.apache.thrift.TBaseHelper.copyBinary(requestParam);
    return this;
  }

  public void unsetRequestParam() {
    this.requestParam = null;
  }

  /** Returns true if field requestParam is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestParam() {
    return this.requestParam != null;
  }

  public void setRequestParamIsSet(boolean value) {
    if (!value) {
      this.requestParam = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case COMMOND:
      if (value == null) {
        unsetCommond();
      } else {
        setCommond((java.lang.String)value);
      }
      break;

    case REQUEST_PARAM:
      if (value == null) {
        unsetRequestParam();
      } else {
        if (value instanceof byte[]) {
          setRequestParam((byte[])value);
        } else {
          setRequestParam((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case COMMOND:
      return getCommond();

    case REQUEST_PARAM:
      return getRequestParam();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case COMMOND:
      return isSetCommond();
    case REQUEST_PARAM:
      return isSetRequestParam();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftRequest)
      return this.equals((ThriftRequest)that);
    return false;
  }

  public boolean equals(ThriftRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_commond = true && this.isSetCommond();
    boolean that_present_commond = true && that.isSetCommond();
    if (this_present_commond || that_present_commond) {
      if (!(this_present_commond && that_present_commond))
        return false;
      if (!this.commond.equals(that.commond))
        return false;
    }

    boolean this_present_requestParam = true && this.isSetRequestParam();
    boolean that_present_requestParam = true && that.isSetRequestParam();
    if (this_present_requestParam || that_present_requestParam) {
      if (!(this_present_requestParam && that_present_requestParam))
        return false;
      if (!this.requestParam.equals(that.requestParam))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCommond()) ? 131071 : 524287);
    if (isSetCommond())
      hashCode = hashCode * 8191 + commond.hashCode();

    hashCode = hashCode * 8191 + ((isSetRequestParam()) ? 131071 : 524287);
    if (isSetRequestParam())
      hashCode = hashCode * 8191 + requestParam.hashCode();

    return hashCode;
  }

  public int compareTo(ThriftRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCommond()).compareTo(other.isSetCommond());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommond()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commond, other.commond);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRequestParam()).compareTo(other.isSetRequestParam());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestParam()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestParam, other.requestParam);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftRequest(");
    boolean first = true;

    sb.append("commond:");
    if (this.commond == null) {
      sb.append("null");
    } else {
      sb.append(this.commond);
    }
    first = false;
    if (isSetRequestParam()) {
      if (!first) sb.append(", ");
      sb.append("requestParam:");
      if (this.requestParam == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.requestParam, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (commond == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'commond' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ThriftRequestStandardScheme getScheme() {
      return new ThriftRequestStandardScheme();
    }
  }

  private static class ThriftRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COMMOND
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.commond = iprot.readString();
              struct.setCommondIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REQUEST_PARAM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.requestParam = iprot.readBinary();
              struct.setRequestParamIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.commond != null) {
        oprot.writeFieldBegin(COMMOND_FIELD_DESC);
        oprot.writeString(struct.commond);
        oprot.writeFieldEnd();
      }
      if (struct.requestParam != null) {
        if (struct.isSetRequestParam()) {
          oprot.writeFieldBegin(REQUEST_PARAM_FIELD_DESC);
          oprot.writeBinary(struct.requestParam);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ThriftRequestTupleScheme getScheme() {
      return new ThriftRequestTupleScheme();
    }
  }

  private static class ThriftRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftRequest> {

    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.commond);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRequestParam()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetRequestParam()) {
        oprot.writeBinary(struct.requestParam);
      }
    }

    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.commond = iprot.readString();
      struct.setCommondIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.requestParam = iprot.readBinary();
        struct.setRequestParamIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

